### ISSUE TITLE
Adding playwright to this container

### ISSUE THREAD

**Issue by SHU-red** [EasyPi/docker-urlwatch#4]
I would love to have a image with the capability to use the [Browser](https://urlwatch.readthedocs.io/en/latest/jobs.html#browser) Job, needing to be able to use playwright

I could not get it working myself

Do you see any chance in providing a docker image for this?

**Comment by vimagick** [comment]
- urlwatch will launch a headless browser: <https://github.com/thp/urlwatch/blob/master/lib/urlwatch/jobs.py#L421-L423>
- We can connect a remote browser: <https://playwright.dev/python/docs/api/class-browsertype#browser-type-connect>

It should be easy to connect to a browser service: <https://www.browserless.io/docs/playwright>

```yaml
name: "A page with JavaScript"
navigate: "https://example.org/"
connect: "wss://chrome.browserless.io/playwright?token=YOUR-API-TOKEN"
```

The `connect` option is easy to add:

```python
class BrowserJob(Job):
    """Retrieve an URL, emulating a real web browser"""

    __kind__ = 'browser'

    __required__ = ('navigate',)

    __optional__ = ('wait_until', 'useragent', 'browser', 'connect')

    def get_location(self):
        return self.user_visible_url or self.navigate

    def set_base_location(self, location):
        self.navigate = location

    def retrieve(self, job_state):
        from playwright.sync_api import sync_playwright
        with sync_playwright() as playwright:
            if self.connect:
                browser = playwright[self.browser or "chromium"].connect(self.connect)
            else:
                browser = playwright[self.browser or "chromium"].launch()
            page = browser.new_page(user_agent=self.useragent)

            if self.wait_until in ('networkidle0', 'networkidle2'):
                logger.warning(f'wait_until has deprecated value of {self.wait_until}, see docs')
                # Pyppetteer -> Playwright migration
                self.wait_until = 'networkidle'

            page.goto(self.navigate, wait_until=self.wait_until)
            return page.content()
```

----

## UPDATED: It's not easy to install playwright inside alpine linux 😭

**Comment by SHU-red** [comment]
Woah nice!
In the meantime i already got my very heavy urlwatch-container running including playwrigth :sweat_smile: 

But yours suggestion is just awesome!

Thanks a lot, ill try this as soon as i can spend time

Thx

**Comment by vimagick** [comment]
If you have a self-hosted browserless service. You can do this:

```yaml
name: "urlwatch homepage"
url: "http://your-self-hosted-browserless.com/content"
user_visible_url: "https://thp.io/2008/urlwatch/"
method: "POST"
headers:
  Content-type: "application/json"
data: '{"url": "https://thp.io/2008/urlwatch/"}'
```

See:
- <https://www.browserless.io/docs/content>
- <https://urlwatch.readthedocs.io/en/latest/advanced.html#sending-arbitrary-data-using-http-put>

**Comment by SHU-red** [comment]
Thank you very much
I will close this topic and try to test your listed solutions as soon as i have time

**Comment by SHU-red** [comment]
> UPDATED: It's not easy to install playwright inside alpine linux

True
Thats why  i created a very big container based on debian

https://hub.docker.com/r/shur3d/urlwatch_playwright

Seems to work but ill test your more microservice based approach using browserless

Thanks

**Comment by SHU-red** [comment]
> If you have a self-hosted browserless service. You can do this:
> 
> ```yaml
> name: "urlwatch homepage"
> url: "http://your-self-hosted-browserless.com/content"
> user_visible_url: "https://thp.io/2008/urlwatch/"
> method: "POST"
> headers:
>   Content-type: "application/json"
> data: '{"url": "https://thp.io/2008/urlwatch/"}'
> ```
> 
> See:
> 
> * https://www.browserless.io/docs/content
> * https://urlwatch.readthedocs.io/en/latest/advanced.html#sending-arbitrary-data-using-http-put

Im sure im using it wrong but im getting back an error
`No connection adapters were found for 'ws://192.168.178.55:3333'`

```
...
---
name: 'Test'
url: 'ws://192.168.178.55:3333'
user_visible_url: 'https://www.myspecialurltotrack.com'
method: 'POST'
headers:
  Content-type: 'application/json'
data: '{"url": "https://www.myspecialurltotrack.com"}'
filter:
  - html2text:
...
```
